### ISSUE TITLE
Can't login, endlessly submitting capture. Can't see feedback whats wrong

### ISSUE THREAD

**Issue by D00mch** [andrikeev/Flow#18]
That's what I see instead of error:
![image](https://github.com/andrikeev/Flow/assets/14236531/6498e68d-2d6a-4d34-883d-3d75358e84bc)

So maybe provide more information in the error message.

**Comment by D00mch** [comment]
I can confirm it works now.

**Comment by andrikeev** [comment]
Fixed in version 4.4.1
